config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'devise/sessions#new'
    get "/users/sign_out" => 'devise/sessions#destroy'
  end

  resources :users do
    resources :uploads
    resources :slideshows
  end

  match 'users/:user_id/uploads/update' => 'uploads#update', :via => :post
  match 'users/:user_id/slideshows/create' => 'slideshows#create', :via => :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slideshow.rb
class Slideshow < ApplicationRecord
  belongs_to :user
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>",:thumb => "100x100>" }

  validates_attachment 	:image,
                        :presence => true,
                        :content_type => { :content_type => /\Aimage\/.*\Z/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :uploads
  has_many :slideshows

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController
  before_action :set_user, only: [:new, :index, :create, :show, :edit, :destroy] 

  def index
    @slideshows = @user.slideshows.all
  end

  def new
  end

  def create
    @slideshow = @user.slideshows.new
    @slideshow[:imgs] = params[:slides]
    if @slideshow.save
      @user.slideshows.push(@slideshow)
      render json: { message: "success"}, :status => 200
      flash[:notice] = "Slideshow successfully created"
      redirect_to root_path
    else
      render json: { error: @slideshow.errors.full_messages.join(',') }, status => 400
    end
  end

  def show
    slideshow = Slideshow.find(params[:id])
    if !slideshow
      format.html {redirect_to slideshows_url, notice: "Slideshow not found"}
      return
    end
    uploads = Upload.all
    @images_publ_ids = slideshow[:imgs].split(";")
  end

  def save
    
  end

  def destroy
    @user.slideshows.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_slideshows_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

 private
    def set_user
      @user = User.find(params[:user_id])
    end
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    @user = User.find(params[:user_id])
    @upload = @user.uploads.create(upload_params)
    if @upload.save
      @upload["public_id"] = Cloudinary::Uploader.upload(@upload.image.path, :format => 'png')["public_id"]
      @user.uploads.push(@upload)
      render json: { message: "success" }, :status => 200
    else
      render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
    end
  end

  def update
    @user = User.find(params["user_id"])
    @upload = @user.uploads.find_by public_id: params["public_id"]
    if @upload == nil
      render json: { error: @upload.errors.full_messages.join(',')}, :status => 404
      return
    end
    @upload["public_id"] = Cloudinary::Uploader.upload(params["new_url"], :format => 'png')["public_id"]
    if @upload.save
      Cloudinary::Uploader.destroy(params["public_id"])
      @user.uploads.push(@upload)
      render json: { message: "success" }, :status => 200
    else
      render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
    end
  end
  
  private
  def upload_params
    params.require(:upload).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :edit, :destroy] 
    
  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoScope</title>
    <script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 70px;">
    <% if user_signed_in? %>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button
		type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
            </button>
	    <%= link_to "PhotoScope", "/users/#{params.has_key?(:user_id) ? params[:user_id] : params[:id]}", :class => "navbar-brand" %> 
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#" data-toggle="modal" data-target="#editImageModal">Upload New</a></li>
              <li><%= link_to "Slideshows", "/users/#{params.has_key?(:user_id) ? params[:user_id] : params[:id]}/slideshows" %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a><%= current_user.email %></a></li>
              <li><%= link_to "Logout", destroy_user_session_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
        
      </nav>
    <% end %>
    <div class="container">
      <div class="jumbotron">
	<%= yield %>
      </div>
    </div>
  </body>
  
  <div class="modal fade" id="editImageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Upload New</h4>
        </div>
        <div class="modal-body">
	  <% if user_signed_in? %>
            <%= form_for([@user, @user.uploads.build], html: { multipart: true, class: "dropzone", id: 'media-dropzone'}) do |f|  %>
	      <div class="fallback">
		<%= f.file_field :image %><br>
		<%= f.submit "Upload" %>
	      </div>
	    <% end %>
	  <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</html>

app/views/slideshows/index.html.erb
<style>
 #line {
   display: inline-block;
 }
</style>

<div align="right"><%= link_to "New slideshow", new_user_slideshow_path, :class => "btn btn-default btn-lg" %></div>
<br />
<div align="center">
  <h3><%= "There isn't any slideshows here ¯\\_(ツ)_/¯" if @slideshows.empty? %> </h3>
  <% @slideshows.each do |slideshow| %>
    <div class="jumbotron" id='slidehow' style='background-color:#ccc'>
      <a id="line" style='text-decoration: none'href="<%= "/users/#{@user.id}/slideshows/#{slideshow.id}"%>" >
	<% slideshow[:imgs].split(";").each do |image_id| %>
	  <%= cl_image_tag image_id, :height => 100, :crop => :thumb, :class => "img img-thumbnail", :id => "slides" %>
	<% end %>
      </a>
      <div id="line"><%= link_to "Delete".html_safe, "/users/#{@user.id}/slideshows/#{slideshow.id}", {:method => :delete, :class => "btn btn-default btn-sm"} %> </div>
    </div>
    <br />
  <% end %>
</div>

app/views/slideshows/new.html.erb
<style>
 #user-images, #slideshow-images {
   list-style-type: none;
   min-height: 80px;
   min-width: 80px;
   border: 1px solid #ccc;
 }
 
 #user-images li, #slideshow-images li{
   vertical-align: top;
   display:inline-block;
 }
 
 .img-thumbnail {
   height: 80px;
 }

</style>

<div>
  <ul id="user-images" class="connectedSortable" style="background-color=#000" >
    <% @user.uploads.all.each do |image|%>
      <li>  <%= cl_image_tag image["public_id"], :id => image["public_id"], :class => "img img-thumbnail", :height => 80 %> </li>
    <% end %>
    <%= " <div align='center'><h2>There isn't any photos here ¯\\_(ツ)_/¯></h2></div>" if @user.uploads.all.empty? %>
  </ul>
  <h3>      Drag photos below</h3>
  <ul id="slideshow-images" class="connectedSortable">
    <!-- <li>Drag photos here</li> -->
  </ul>
  
  <button id="okButton" class="btn btn-default btn-lg">Save</button>

</div>

<script type='text/javascript'>
 $( "#user-images, #slideshow-images" ).sortable({
   connectWith: ".connectedSortable"
 }).disableSelection();
 $("#okButton").bind("click", function () {
   var items = $("#slideshow-images li img");
   var result = "";
   for (var i = 0; i < items.length; i++) {
     result += items.get(i).id + ";";
   }
   var url = "/users/<%= @user.id %>/slideshows/create";
   var indexes = {'slides': result};
   $.ajax({
     type: "POST",
     url: url,
     dataType: 'json',
     data: indexes
   });    
 })
</script>

app/views/slideshows/show.html.erb
<ul class="bxslider">
  <% @images_publ_ids.each do |image| %>
    <li>
      <%= cl_image_tag image, :height => 600, :width => 1100, :crop => :pad %>
    </li>
  <% end %>
</ul>



<script type='text/javascript'>
 $('.bxslider').bxSlider({
   auto: true,
   autoControls: true
 });
</script>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% if !user_signed_in? %>
    <%= link_to 'Log in', new_user_session_path %><br>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>

<% @user.uploads.all.each do |image|%>
  <a onclick="return launchEditor('<%=image["public_id"]%>', '<%= "http://res.cloudinary.com/alex-pat-test-cloud/image/upload/v1469210070/#{image["public_id"]}.png"%>');"><%= cl_image_tag image["public_id"], :id => image["public_id"], :height => 200, :crop => :thumb, :class => "img img-thumbnail" %></a>
<% end %>
<div align="center"><h2><%= "There isn't any photos here ¯\\_(ツ)_/¯" if @user.uploads.all.empty? %></h2></div>



<!— Instantiate Feather —>
<script type='text/javascript'>
 var featherEditor = new Aviary.Feather({
   apiKey: '0728ddae97b84c04bcd6adf4ef7fd5dc',
   apiVersion: 3,
   theme: 'light', // Check out our new 'light' and 'dark' themes!
   tools: 'all',
   fileFormat: 'png',
   appendTo: '',
   onSave: function(imageID, newURL) {
     var img = document.getElementById(imageID);
     img.src = newURL;

     var url = '/users/<%= @user.id %>/uploads/update';
     var sendable = {'public_id': imageID, 'new_url': newURL};
     $.ajax({
       type: "POST",
       url: url,
       dataType: 'json',
       data: sendable
     });
   },
   onError: function(errorObj) {
     alert(errorObj.message);
   }
 });
 function launchEditor(id, src) {
   featherEditor.launch({
     image: id,
     url: src
   });
   return false;
 }
</script>